### ISSUE TITLE
ResultSet Hook

### ISSUE THREAD

**Issue by sggreener** [sggreener/GeoRaptor#11]
I cannot see how to implement the necessary code via which GeoRaptor's RenderResultSet class (package org.GeoRaptor.OracleSpatial.Grid) can hook into a resultSet grid. @PhilippSalvisberg can you look into how to make this functionality work (I thought you did this 6+ months ago)? The RenderResultSet code in the master/origin is the same as in the latest data-initial branch. (Data-initial contains code that has been made to work, the original master/origin was missing quite a bit - removed by the Uni students to help their understanding.)

**Comment by PhilippSalvisberg** [comment]
I've done that as an example only. See https://github.com/PhilippSalvisberg/sqldev/blob/main/workshop/110_grid_table_menu/README.md#extend-context-menu-of-grid-table . Based on that you should be able to apply that in this project.

**Comment by sggreener** [comment]
Philipp,
Thanks for the link.
I will have a go to see what I can do.
Simon

**Comment by sggreener** [comment]
@PhilippSavisberg I have successfully implemented the resultSet hook and gotten a column renderer to work.

Thanks for all your help on this.

regards
Simon
